### ISSUE TITLE
Draft create should check for draft init

### ISSUE THREAD

**Issue by razfriman** [Azure/draft#925] opened 2019-02-16 05:53 UTC
I tried to create a draft for my project. after doing a fresh `brew` install of draft.
My first error was 
> Error: no languages were detected

So I forced the language to `csharp`. Then I see:
> Error: No packs found with name csharp

Had to go into the docs to see that you need to first run`draft init` to get the default plugins.

It would be nice for draft to do a check for this, or update the message to tell you that you forgot to init it

**Comment by bacongobbler** [comment] 2020-04-28 17:14
duplicate of #900.

**Closed by bacongobbler** 2020-04-28 17:14 UTC
Labels: area/client, enhancement
