### ISSUE TITLE
--ingress-enabled ignored when using Minikube

### ISSUE THREAD

**Issue by alexpilotti** [Azure/draft#420] opened 2017-10-23 22:07 UTC
Unlike previous versions, ingress is always disabled when using Minikube (tested on v0.7.0), apparently --ingress-enabled gets ignored.

**Comment by bacongobbler** [comment] 2017-10-23 22:15
closing as a duplicate of #336. I've submitted #419 that should assist in getting to the bottom of this. Thanks!

**Closed by bacongobbler** 2017-10-23 22:15 UTC
