### ISSUE TITLE
Various Draft commands fail due to unmarshaling error

### ISSUE THREAD

**Issue by radu-matei** [Azure/draft#682] opened 2018-04-20 18:54 UTC
How to reproduce:

- build Draft off master
- `draft version`

```
$ draft version
failed to load plugins: error unmarshaling JSON: json: cannot unmarshal string into Go struct field Metadata.hooks of type plugin.Hooks&version.Version{SemVer:"canary", GitCommit:"779c70aee94704aba978136b7a7a88c9881f8a21", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment] 2018-04-20 19:12
This might be due to the recent change merged into master: #658. Can you try rebasing off master and re-run `draft init`?

**Comment by radu-matei** [comment] 2018-04-20 19:15
I'm off master, up to date.
Same thing with `draft init`:

```
$ draft init
Installing default plugins...
Error: error unmarshaling JSON: json: cannot unmarshal string into Go struct field Metadata.
hooks of type plugin.Hooks
```

**Comment by bacongobbler** [comment] 2018-04-20 19:27
Oh! It might be due to CI not being hooked up once we moved over to https://github.com/draftcreate/draft-pack-repo, so the latest changes merged into draft-pack-repo weren't actually published. Lemme see if I can reproduce.

**Comment by bacongobbler** [comment] 2018-04-20 19:28
If that's the case then once @michelleN's done hooking up CI, this should be fixed.

**Comment by bacongobbler** [comment] 2018-04-20 19:33
oh hrm, it's actually because `draft init` installs 0.3.1 no matter if you use the canary release of draft-pack-repo or not.

```
><> cat ~/.draft/cache/plugins/https-github.com-Azure-draft-pack-repo/plugin.yaml 
name: "pack-repo"
version: "0.3.1"
usage: "The Draft pack repository plugin"
description: "The Draft pack repository plugin"
command: "$DRAFT_PLUGIN_DIR/bin/pack-repo"
hooks:
  install: "$DRAFT_PLUGIN_DIR/scripts/get.sh"
```

I forgot we changed that in #490. I guess in that case, we'll need to cut a new release of draft-pack-repo with powershell support then bump https://github.com/Azure/draft/blob/779c70aee94704aba978136b7a7a88c9881f8a21/pkg/plugin/builtins.go#L12 to 0.4.0.

**Comment by radu-matei** [comment] 2018-04-20 20:00
Thanks for looking into this, @bacongobbler!

**Closed** 2018-04-23 15:57 UTC

**Comment by radu-matei** [comment] 2018-04-23 16:16
Didn't have time to investigate what's happening, but here's the output:

```
$ draft init
Installing default plugins...
Downloading https://azuredraft.blob.core.windows.net/draft/pack-repo-0.4.0-darwin-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   215  100   215    0     0    370      0 --:--:-- --:--:-- --:--:--   370
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
!!!     Failed to install draft-pack-repo
!!!     For support, go to https://github.com/draftcreate/draft-pack-repo.
Error: plugin install hook for "pack-repo" exited with error
```

**Comment by bacongobbler** [comment] 2018-04-23 16:36
Seems like circleci for draft-pack-repo isn't uploading tags. For now I've manually uploaded the release assets up to blob storage, but I'll open a ticket in draft-pack-repo to automate this process.

**Comment by bacongobbler** [comment] 2018-04-23 16:37
Done.

**Comment by sabbour** [comment] 2018-06-04 12:16
Is this really fixed?

I'm having the same issue on 0.15.0:

```
draft version
failed to load plugins: error unmarshaling JSON: json: cannot unmarshal string into Go struct field Metadata.hooks of type plugin.Hooks&version.Version{SemVer:"v0.15.0", GitCommit:"9d73889a1318a435d126bc5df846610d30cfbe7f", GitTreeState:"clean"}
```

**Comment by sabbour** [comment] 2018-06-04 12:45
@radu-matei I deleted draft using `brew uninstall --force draft` and then installed it again and still faced the issue.

It got fixed when I followed the workaround above https://github.com/Azure/draft/issues/682#issuecomment-383211295

Can we have a look at this?

**Comment by radu-matei** [comment] 2018-06-04 13:31
Yeah, I'm not sure if `brew uninstall` deletes the `~/.draft` directory

**Comment by bacongobbler** [comment] 2018-06-04 14:27
`brew uninstall` does not or cannot delete anything under $HOME so that has to be cleaned up manually
