### ISSUE TITLE
Format, colors on VS Code PowerShell terminal

### ISSUE THREAD

**Issue by radu-matei** [Azure/draft#616] opened 2018-03-27 17:41 UTC
If you open the VS Code terminal on Windows and create a PowerShell tab, the output from `draft up` looks like:

```
draft up --auto-connect
?[94;40;4mDraft Up Started?[0m: '?[36;40mexample-go?[0m'?[36;40mexample-go?[0m: ?[92;40;1mBuilding Docker Image?[0m: SUCCESS ⚓  (6.0050s)
?[36;40mexample-go?[0m: ?[92;40;1mPushing Docker Image?[0m: SUCCESS ⚓  (11.0087s)
?[36;40mexample-go?[0m: ?[92;40;1mReleasing Application?[0m: SUCCESS ⚓  (0.8322s)?[36;40mexample-go?[0m: ?[94;40;4mBuild ID?[0m: ?[93;40;1m01C9M8J0B2MWFDSSZ24N9SD24Q?[0m
?[94;40;4mInspect the logs with?[0m `?[93;40;1mdraft logs 01C9M8J0B2MWFDSSZ24N9SD24Q?[0m`
```

**Comment by bacongobbler** [comment] 2018-03-27 17:52
I'm going to close this as a duplicate of https://github.com/Azure/draft/issues/303#issuecomment-329672743, but thank you for opening this! It appears to be an issue for both CMD and Powershell, but not for cmder since it seems to handle terminal color escape codes. If we can tackle the user scnenarios Matt described in that ticket, it should solve this problem for Powershell as well. :)

**Closed by bacongobbler** 2018-03-27 17:52 UTC
