### ISSUE TITLE
Support for client.authentication.k8s.io/v1beta1

### ISSUE THREAD

**Issue by geeckmc** [Azure/draft#942] opened 2019-07-24 14:45 UTC
Command
`$ draft up`

Errors :
 `$ Error: Could not get a kube client: could not get Kubernetes client: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1beta1"`

Comments: 
> It seems that the implementation of your Kube client does not support the new v1beta1 authentication method.

**Comment by jfmatth** [comment] 2019-09-12 03:53
I get the same error with Digital Ocean's K8s, but works fine with Minikube

**Comment by jfmatth** [comment] 2019-09-13 23:27
I was able to get around this error.  Seems like the method that DigitalOcean uses isn't compatible for the v1beta.

I got around by specifying a kube.yml file via the KUBECONFIG variable.

**Comment by bacongobbler** [comment] 2020-04-28 17:09
duplicate of #956

**Closed by bacongobbler** 2020-04-28 17:09 UTC
