### ISSUE TITLE
panic: repeated read on failed websocket connection

### ISSUE THREAD

**Issue by Gouthamve** [Azure/draft#160] opened 2017-06-19 04:19 UTC
Hi, draft crashed with the following panic:

```
time="2017-06-19T04:14:42Z" level=info msg="server is now listening at tcp://0.0.0.0:44135" 
time="2017-06-19T04:14:55Z" level=info msg="POST /apps/prometheus-operator" 
panic: repeated read on failed websocket connection

goroutine 20 [running]:
panic(0x12ad220, 0xc420132f00)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/Azure/draft/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc4202ec000, 0x0, 0xc420595680, 0xabd2e4, 0x180001, 0x0)
	/home/jenkins/go/src/github.com/Azure/draft/vendor/github.com/gorilla/websocket/conn.go:893 +0x16d
github.com/Azure/draft/vendor/github.com/gorilla/websocket.(*Conn).ReadMessage(0xc4202ec000, 0x8, 0xc4200dffa0, 0x1e, 0x1e, 0xed0d946e1, 0xc4083e7c80)
	/home/jenkins/go/src/github.com/Azure/draft/vendor/github.com/gorilla/websocket/conn.go:954 +0x2f
github.com/Azure/draft/api.pingClient(0xc4202ec000, 0xc4202e8180)
	/home/jenkins/go/src/github.com/Azure/draft/api/server.go:527 +0x40
created by github.com/Azure/draft/api.serveWs
	/home/jenkins/go/src/github.com/Azure/draft/api/server.go:290 +0xa8f
```

**Comment by bacongobbler** [comment] 2017-06-19 06:37
Closing as a duplicate of #79.

**Closed by bacongobbler** 2017-06-19 06:37 UTC
