### ISSUE TITLE
Will there be support for C# on .NET Core?

### ISSUE THREAD

**Issue by chzbrgr71** [Azure/draft#87] opened 2017-06-01 15:31 UTC

**Comment by ultimateboy** [comment] 2017-06-01 15:32
Related: https://github.com/Azure/draft/issues/84

**Comment by bacongobbler** [comment] 2017-06-01 16:03
Closing as a duplicate of #84 but please let me know if this is a separate request and we can happily re-open this. Thanks!

**Closed by bacongobbler** 2017-06-01 16:03 UTC
Labels: area/defaultpacks
