### ISSUE TITLE
send on closed channel

### ISSUE THREAD

**Issue by rnkhouse** [Azure/draft#850] opened 2018-07-31 19:18 UTC
>draft up
Draft Up Started: 'app': 01CKRWB5Q3XRDD3P8GJQND44QF
helmdemo: Building Docker Image: SUCCESS ⚓  (1.0018s)
helmdemo: Pushing Docker Image -panic: send on closed channel

goroutine 37 [running]:
github.com/Azure/draft/pkg/builder/docker.(*Builder).Push.func1.1(0xc0422caf20, 0xc042306050, 0x24aed00, 0xc04204e0a0, 0xc0422caf64, 0x4, 0xc042978040, 0xc0422b13b0, 0xc042972040, 0x40)
        /go/src/github.com/Azure/draft/pkg/builder/docker/builder.go:127 +0x2b6
created by github.com/Azure/draft/pkg/builder/docker.(*Builder).Push.func1
        /go/src/github.com/Azure/draft/pkg/builder/docker/builder.go:115 +0x150

**Comment by bacongobbler** [comment] 2018-08-04 18:59
can you please give us more information on

- `draft version`
- `draft config list`

Any information you can provide on how you received this error would be helpful as well.

**Comment by rnkhouse** [comment] 2018-08-07 14:37
>&version.Version{SemVer:"v0.15.0", GitCommit:"9d73889a1318a435d126bc5df846610d30cfbe7f", GitTreeState:"clean"}

>registry        mtesacr.azurecr.io

**Comment by bacongobbler** [comment] 2018-08-07 16:06
Aha, this looks like a duplicate of #811. I'm going to close this in favour of that one so we're all working on a single ticket. Thanks!

**Closed by bacongobbler** 2018-08-07 16:06 UTC
Labels: area/client
