### ISSUE TITLE
Docker build that needs arguments

### ISSUE THREAD

**Issue by vpod** [Azure/draft#722] opened 2018-05-04 07:17 UTC
I want to build app that needs extra build arguments to Docker. In my case, it is JAVA_TOOL_OPTIONS to pass corporate proxy settings to Gradle.
Looking at the docs I see option to pass settings to Helm, but not to docker.
As a workaround I could hardcode the parameters in the Dockerfile, but this is not the best way in my opinion.
Is there a way to pass --build-arg to Docker during build?
I've been checking help of version: &version.Version{SemVer:"v0.14.0", GitCommit:"e7a92f6b2f05a23f4cd9cc15fc24eb98d628e5d7", GitTreeState:"clean"}.

**Comment by bacongobbler** [comment] 2018-05-05 08:00
Hey @vpod, this is currently not possible but it's being tracked in #663. If you'd like to take a crack at it, we'd be happy to help point you in the right direction to write this feature.

Because this has been brought up in an earlier ticket I'm going to close this as a duplicate of #663. Let's carry on the conversation over there. Thanks! :)

**Closed by bacongobbler** 2018-05-05 08:00 UTC
