### ISSUE TITLE
Cant use draft with csharp

### ISSUE THREAD

**Issue by profesor79** [Azure/draft#392] opened 2017-10-11 21:55 UTC
Hi guys,
is there a way to get why daraft cannot pack c#?
And also why c# is recognized as xml?

![draftcsharp](https://user-images.githubusercontent.com/11340526/31468729-f1fe328c-aed6-11e7-8a5b-e0a2669e3481.png)

I checked it with go language and it works, so this is not a local setup issue I suppose

![image](https://user-images.githubusercontent.com/11340526/31468785-3e100010-aed7-11e7-9747-831077132c66.png)

**Comment by bacongobbler** [comment] 2017-10-12 15:24
Hey @profesor79! Can you give us more information on what version of draft you're running?

**Comment by bacongobbler** [comment] 2017-10-12 15:25
Curious that in your first screenshot it looks like the path it's looking for is `...\.draft\packs\ack=csharp`. I haven't seen that before.

**Comment by bacongobbler** [comment] 2017-10-18 17:59
Hmm. `draft create` works just fine for me using the example ASP.NET application.

```
PS C:\Users\mafishe\go\src\github.com\Azure\draft\examples\csharp> draft create
--> Draft detected the primary language as csharp with 84.861307% certainty.
--> Ready to sail
```

Do you have a public repository that we can use to test against?

**Comment by bacongobbler** [comment] 2017-10-18 18:03
One PR that may assist with the language being detected as XML would be #344. If there is a large amount of code in your .csproj files then linguist is going to detect that a large majority of your codebase is written in XML. Once #344 is finalized and merged, you can fix this by writing out the following .gitattributes file in the root of your application:

```
*.csproj linguist-language=csharp
```

**Comment by bacongobbler** [comment] 2017-10-25 21:29
ping, any news on this front?

**Comment by profesor79** [comment] 2017-10-25 21:46
pong - will try to check that tomorrow and will revert here.

**Comment by bacongobbler** [comment] 2017-12-29 08:15
I'm going to close this issue due to inactivity and due to lack of being able to reproduce the issue locally, but please feel free to re-open and report back once you get an idea how it occurred. Thanks!

**Closed by bacongobbler** 2017-12-29 08:15 UTC
Labels: question/support
