### ISSUE TITLE
draft  create --pack=foo does not copy the .dockerignore from the pack

### ISSUE THREAD

**Issue by jstrachan** [Azure/draft#477] opened 2018-01-05 12:20 UTC
with a blank java project and typing:
```
draft  create --pack=github.com/Azure/draft/packs/java
```
there's no .dockerignore file copied across, despite them being one in the pack at `~/.draft/packs/github.com/Azure/draft/packs/java/.dockerignore`.

While the build still works, it means that this dockerfile line https://github.com/Azure/draft/blob/master/packs/java/Dockerfile#L3 will copy all git history + `target` dir (so all pervious builds/tests/results/logs etc) which slows down the docker build.

**Comment by bacongobbler** [comment] 2018-01-05 17:24
closing as a duplicate of #427, which will be fixed via #453.

**Closed by bacongobbler** 2018-01-05 17:24 UTC
