### ISSUE TITLE
Examples: dotnetcore app downloads on chrome/macos as .gz file.

### ISSUE THREAD

**Issue by squillace** [Azure/draft#243] opened 2017-08-08 07:38 UTC
Waiting for that Hello world greeting, and I get:

![screen shot 2017-08-08 at 12 37 39 am](https://user-images.githubusercontent.com/1422718/29061235-d8f0db42-7bd1-11e7-87ef-0e9d25cd2d1a.png)

**Comment by squillace** [comment] 2017-08-08 16:22
![image](https://user-images.githubusercontent.com/1422718/29082651-0113e800-7c1b-11e7-82da-de8c463a0712.png)

**Comment by bacongobbler** [comment] 2017-08-15 22:39
I was unable to reproduce this with v0.6.0-rc2 so I imagine this has been fixed with #205 or some other PR. After I release an RC3, @squillace would you be able to test and confirm?

I hit #260, but that issue is unrelated to this so we can track that issue separately.

Screenshot for proof:

<img width="2560" alt="screen shot 2017-08-15 at 3 36 11 pm" src="https://user-images.githubusercontent.com/1360539/29339573-ac27a916-81cf-11e7-89a8-ff03cf7d0cf0.png" />

**Closed** 2017-08-16 22:29 UTC
